#  Manipulação de Arquivos e dados em Python

## Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Se quiserem fazer fora do Cocalc
lispoktab=pd.read_html( "https://pt.wikipedia.org/wiki/Lista_de_epis%C3%B3dios_de_Pok%C3%A9mon")

In [3]:
len(lispoktab)

54

In [4]:
lispoktab[1]

   Temporada               Geração                    Título nos EUA  \
   Temporada Temporada.1   Geração                    Título nos EUA
0        NaN          01  Primeira                     Indigo League
1        NaN          02  Primeira  Adventures in the Orange Islands
2        NaN          03   Segunda                The Johto Journeys
3        NaN          04   Segunda            Johto League Champions
4        NaN          05   Segunda                      Master Quest
5        NaN          06  Terceira                          Advanced
6        NaN          07  Terceira                Advanced Challenge
7        NaN          08  Terceira                   Advanced Battle
8        NaN          09  Terceira                   Battle Frontier
9        NaN          10    Quarta                 Diamond and Pearl
10       NaN          11    Quarta                  Battle Dimension
11       NaN          12    Quarta                  Galactic Battles
12       NaN          13    Quarta             Sinnoh League Victors
13       NaN          14    Quinta                     Black & White
14       NaN          15    Quinta                   Rival Destinies
15       NaN          16    Quinta               Adventures in Unova
16       NaN          16    Quinta    Adventures in Unova and Beyond
17       NaN          17     Sexta                                XY
18       NaN          18     Sexta                       Kalos Quest
19       NaN          19     Sexta                               XYZ
20       NaN          20    Sétima                        Sun & Moon
21       NaN          21    Sétima                  Ultra Adventures
22       NaN          22    Sétima                     Ultra Legends
23       NaN          23    Oitava                          Journeys
24       NaN          24    Oitava                   Master Journeys
25       NaN          25    Oitava                 Ultimate Journeys
26       NaN    Especial    Oitava            To Be a Pokémon Master
27       NaN          26      Nona                          Horizons

                  Titulo no Brasil Episódios              \
                  Titulo no Brasil Episódios Episódios.1
0                      Liga Índigo        82          82
1      Aventuras nas Ilhas Laranja        36          36
2                  A Jornada Johto        41          41
3           Campeões da Liga Johto        52          52
4                     Master Quest        65          65
5                         Avançado        40          40
6                 Desafio Avançado        52          52
7                 Batalha Avançada        54          54
8             Batalha da Fronteira        47          47
9                Diamante e Pérola        52          52
10             Batalha Dimensional        52          52
11             Batalhas Galácticas        53          53
12       Vencedores da Liga Sinnoh        34          34
13                  Preto e Branco        50          50
14                 Destinos Rivais        49          49
15              Aventuras em Unova        25          45
16  Aventuras em Unova e Mais Além        20          45
17                              XY        49          49
18                Desafio em Kalos        44          44
19                             XYZ        47          47
20                       Sol e Lua        43          43
21                 Ultra Aventuras        49          49
22                    Ultra Lendas        54          54
23                        Jornadas        48          48
24              Jornadas de Mestre        42          42
25               Jornadas Supremas        46          46
26                  Mestre Pokémon        11          11
27                      Horizontes        24          24

         Exibição original
                   Estreia                   Final
0       1 de abril de 1997   21 de janeiro de 1999
1    28 de janeiro de 1999    7 de outubro de 1999
2    14 de outubro de 1999     27 de julho de 2000
3      3 de agosto de 2000     2 de agosto de 2001
4      9 de agosto de 2001  14 de novembro de 2002
5   21 de novembro de 2002    28 de agosto de 2003
6    4 de setembro de 2003   2 de setembro de 2004
7    9 de setembro de 2004  29 de setembro de 2005
8     6 de outubro de 2005  14 de setembro de 2006
9   28 de setembro de 2006   25 de outubro de 2007
10   8 de novembro de 2007   4 de dezembro de 2008
11   4 de dezembro de 2008  24 de dezembro de 2009
12    7 de janeiro de 2010   9 de setembro de 2010
13  23 de setembro de 2010  15 de setembro de 2011
14  22 de setembro de 2011    4 de outubro de 2012
15   11 de outubro de 2012     18 de abril de 2013
16     25 de abril de 2013  26 de setembro de 2013
17   17 de outubro de 2013   30 de outubro de 2014
18   6 de novembro de 2014   22 de outubro de 2015
19   29 de outubro de 2015   3 de novembro de 2016
20  17 de novembro de 2016  21 de setembro de 2017
21    5 de outubro de 2017   14 de outubro de 2018
22   21 de outubro de 2018   3 de novembro de 2019
23  17 de novembro de 2019   4 de dezembro de 2020
24  11 de dezembro de 2020  10 de dezembro de 2021
25  17 de dezembro de 2021  16 de dezembro de 2022
26   13 de janeiro de 2023     24 de março de 2023
27     14 de abril de 2023                presente

In [5]:
df=lispoktab[1]

In [17]:


df.columns

MultiIndex([(        'Temporada',        'Temporada'),
            (        'Temporada',      'Temporada.1'),
            (          'Geração',          'Geração'),
            (   'Título nos EUA',   'Título nos EUA'),
            ( 'Titulo no Brasil', 'Titulo no Brasil'),
            (        'Episódios',        'Episódios'),
            (        'Episódios',      'Episódios.1'),
            ('Exibição original',          'Estreia'),
            ('Exibição original',            'Final')],
           )

In [24]:
df.columns=[segunda for (primeira, segunda) in df.columns]

ValueError: ignored

In [26]:
df.columns

Index(['Temporada', 'Temporada.1', 'Geração', 'Título nos EUA',
       'Titulo no Brasil', 'Episódios', 'Episódios.1', 'Estreia', 'Final'],
      dtype='object')

In [27]:
df2=df[[ 'Temporada.1', 'Geração', 'Título nos EUA',
       'Titulo no Brasil', 'Episódios.1', 'Estreia', 'Final']]

In [29]:
df2.columns=['Temporada', 'Geração', 'Título nos EUA',
       'Titulo no Brasil', 'Episódios', 'Estreia', 'Final']

In [30]:
df2

,Temporada,Geração,Título nos EUA,Titulo no Brasil,Episódios,Estreia,Final
0,01,Primeira,Indigo League,Liga Índigo,82,1 de abril de 1997,21 de janeiro de 1999
1,02,Primeira,Adventures in the Orange Islands,Aventuras nas Ilhas Laranja,36,28 de janeiro de 1999,7 de outubro de 1999
2,03,Segunda,The Johto Journeys,A Jornada Johto,41,14 de outubro de 1999,27 de julho de 2000
3,04,Segunda,Johto League Champions,Campeões da Liga Johto,52,3 de agosto de 2000,2 de agosto de 2001
4,05,Segunda,Master Quest,Master Quest,65,9 de agosto de 2001,14 de novembro de 2002
5,06,Terceira,Advanced,Avançado,40,21 de novembro de 2002,28 de agosto de 2003
6,07,Terceira,Advanced Challenge,Desafio Avançado,52,4 de setembro de 2003,2 de setembro de 2004
7,08,Terceira,Advanced Battle,Batalha Avançada,54,9 de setembro de 2004,29 de setembro de 2005
8,09,Terceira,Battle Frontier,Batalha da Fronteira,47,6 de outubro de 2005,14 de setembro de 2006
9,10,Quarta,Diamond and Pearl,Diamante e Pérola,52,28 de setembro de 2006,25 de outubro de 2007
10,11,Quarta,Battle Dimension,Batalha Dimensional,52,8 de novembro de 2007,4 de dezembro de 2008
11,12,Quarta,Galactic Battles,Batalhas Galácticas,53,4 de dezembro de 2008,24 de dezembro de 2009
12,13,Quarta,Sinnoh League Victors,Vencedores da Liga Sinnoh,34,7 de janeiro de 2010,9 de setembro de 2010
13,14,Quinta,Black & White,Preto e Branco,50,23 de setembro de 2010,15 de setembro de 2011
14,15,Quinta,Rival Destinies,Destinos Rivais,49,22 de setembro de 2011,4 de outubro de 2012
15,16,Quinta,Adventures in Unova,Aventuras em Unova,45,11 de outubro de 2012,18 de abril de 2013
16,16,Quinta,Adventures in Unova and Beyond,Aventuras em Unova e Mais Além,45,25 de abril de 2013,26 de setembro de 2013
17,17,Sexta,XY,XY,49,17 de outubro de 2013,30 de outubro de 2014
18,18,Sexta,Kalos Quest,Desafio em Kalos,44,6 de novembro de 2014,22 de outubro de 2015
19,19,Sexta,XYZ,XYZ,47,29 de outubro de 2015,3 de novembro de 2016
20,20,Sétima,Sun & Moon,Sol e Lua,43,17 de novembro de 2016,21 de setembro de 2017
21,21,Sétima,Ultra Adventures,Ultra Aventuras,49,5 de outubro de 2017,14 de outubro de 2018
22,22,Sétima,Ultra Legends,Ultra Lendas,54,21 de outubro de 2018,3 de novembro de 2019
23,23,Oitava,Journeys,Jornadas,48,17 de novembro de 2019,4 de dezembro de 2020
24,24,Oitava,Master Journeys,Jornadas de Mestre,42,11 de dezembro de 2020,10 de dezembro de 2021
25,25,Oitava,Ultimate Journeys,Jornadas Supremas,46,17 de dezembro de 2021,16 de dezembro de 2022
26,Especial,Oitava,To Be a Pokémon Master,Mestre Pokémon,11,13 de janeiro de 2023,24 de março de 2023
27,26,Nona,Horizons,Horizontes,24,14 de abril de 2023,presente

## Perguntas

Quantas regiões diferentes existem?

In [31]:
len(set(df2["Geração"]))

KeyError: ignored

Construa uma coluna com o número de episódios.

In [ ]:
strepisodios=df2["Episódios"][0]

lis=strepisodios.split("-")
lis2=[int(elem) for elem in lis]
lis2[1]-lis2[0]+1

82

In [ ]:
strepisodios=df2["Episódios"][0]
lis=strepisodios.split("-")
lis2=[int(elem) for elem in lis]
lis2[1]-lis2[0]+1

83

In [ ]:
def geraduracao(string):
    lis=string.split("-")
    lis2=[int(elem) for elem in lis]
    return lis2[1]-lis2[0]+1

In [ ]:
teste=(df2["Episódios"].apply(geraduracao))
df2["Duração"]=teste

/usr/local/lib/python3.6/dist-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [ ]:
df2

,Série,Geração,Temporada,Descrição,Episódios,Região,Duração
0,Série Original (O Início/Ouro e Prata),Primeira (O Início),Liga Índigo,O treinador novato Ash Ketchum começa sua jorn...,001-083,Kanto,83
1,Série Original (O Início/Ouro e Prata),Primeira (O Início),Aventuras nas Ilhas Laranja,Depois de competir na Liga Índigo e não ter o ...,084-118,Ilhas Laranja,35
2,Série Original (O Início/Ouro e Prata),Segunda (Ouro e Prata),Liga Johto,Quando o Professor Carvalho não consegue desco...,119-159,Johto,41
3,Série Original (O Início/Ouro e Prata),Segunda (Ouro e Prata),Campeões da Liga Johto,Continua com as aventuras de Ash e seus amigos...,160-211,Johto,52
4,Série Original (O Início/Ouro e Prata),Segunda (Ouro e Prata),Master Quest,"Ash, Misty e Brock em sua jornada descobrem um...",212-276,Johto,65
5,Rubi e Safira,Terceira,Pokémon: Avançado,Inicia as Aventuras de Ash e Brock em Hoenn. N...,277-316,Hoenn,40
6,Rubi e Safira,Terceira,Desafio Avançado,Continua com a jornada de Ash e seus amigos em...,317-368,Hoenn,52
7,Rubi e Safira,Terceira,Batalha Avançada,As equipes Magma e Aqua despertam Groudon e Ky...,369-422,Hoenn,54
8,Rubi e Safira,Terceira,Batalha da Fronteira,Conclui a Jornada na Batalha da Fronteira. May...,423-469,Kanto,47
9,Diamante e Pérola,Quarta,Diamante e Pérola,Inicia as aventuras de Ash e Brock em Sinnoh c...,470-521,Sinnoh,52
10,Diamante e Pérola,Quarta,Batalha Dimensional,"Continua as aventuras de Ash, Brock e Dawn em ...",522-573,Sinnoh,52
11,Diamante e Pérola,Quarta,Batalhas Galácticas,"Continua a jornada de Ash, Dawn e Brock em Sin...",574-626,Sinnoh,53
12,Diamante e Pérola,Quarta,Vencedores da Liga Sinnoh,"Conclui a jornada de Ash, Dawn e Brock em Sinn...",627-660,Sinnoh,34
13,Preto e Branco,Quinta,Preto e Branco,Inicia as aventuras de Ash na região de Unova ...,661-708,Unova,48
14,Preto e Branco,Quinta,Destinos Rivais,Ash reencontra Dawn e Cynthia. Ash e seus amig...,709-757,Unova,49
15,Preto e Branco,Quinta,Aventuras em Unova (e Mais Além),"Continua a jornada de Ash, Iris e Cilan em Uno...",758-804,Unova,47
16,XY,Sexta,A Série XY,Inicia as aventuras de Ash na região de Kalos ...,805-853,Kalos,49
17,XY,Sexta,Desafio em Kalos,"Continua as aventuras de Ash, Serena, Clemont ...",854-898,Kalos,45
18,XY,Sexta,A Série: XY & Z,"Continua a saga de Ash ,Clement, Bonnie e Sere...",899-951,Kalos,53
19,Sol e Lua,Sétima,Sol e Lua,"Inicia as aventuras de Ash, Victória, Lulú, Ki...",952-994,Alola,43

In [ ]:
gb=df2.groupby("Região")

In [ ]:

gb["Geração"].count()

Região
Alola            1
Hoenn            3
Ilhas Laranja    1
Johto            3
Kalos            3
Kanto            2
Sinnoh           4
Unova            3
Name: Geração, dtype: int64

In [ ]:
gb["Duração"].mean()

Região
Alola            43.000000
Hoenn            48.666667
Ilhas Laranja    35.000000
Johto            52.666667
Kalos            49.000000
Kanto            65.000000
Sinnoh           47.750000
Unova            48.000000
Name: Duração, dtype: float64

## Exercícios

- Calcule o número de episódios em cada geração.

## Exemplo Tenis

### Para baixar os programas use o comando (não será necessário no SageMathCloud)

In [ ]:
%%sh

git clone https://github.com/ipython-books/cookbook-data.git
cd cookbook-data
unzip tennis.zip

Archive:  tennis.zip
  inflating: data/Andy-Murray.csv
  inflating: data/Novak-Djokovic.csv
  inflating: data/Rafael-Nadal.csv
  inflating: data/Roger-Federer.csv

Cloning into 'cookbook-data'...

In [ ]:
import numpy as np
import pandas as pd
player = 'Roger Federer'
filename = "./cookbook-data/data/{name}.csv".format(name=player.replace(' ', '-'))
df = pd.read_csv(filename)

In [ ]:
df

WARNING: Some output was deleted.

In [ ]:
df.columns

Index(['year', 'tournament', 'start date', 'type', 'surface', 'draw',
       'atp points', 'atp ranking', 'tournament prize money', 'round',
       'opponent', 'ranking', 'score', 'stats link', 'tournament.1',
       'tournament round', 'time', 'winner', 'player1 name',
       'player1 nationality', 'player1 aces', 'player1 double faults',
       'player1 1st serves in', 'player1 1st serves total',
       'player1 1st serve points won', 'player1 1st serve points total',
       'player1 2nd serve points won', 'player1 2nd serve points total',
       'player1 break points won', 'player1 break points total',
       'player1 service games played', 'player1 1st serve return points won',
       'player1 1st serve return points total',
       'player1 2nd serve return points won',
       'player1 2nd serve return points total',
       'player1 break points converted won',
       'player1 break points converted total', 'player1 return games played',
       'player1 total service points won',
       'player1 total service points total', 'player1 total return points won',
       'player1 total return points total', 'player1 total points won',
       'player1 total points total', 'player2 name', 'player2 nationality',
       'player2 aces', 'player2 double faults', 'player2 1st serves in',
       'player2 1st serves total', 'player2 1st serve points won',
       'player2 1st serve points total', 'player2 2nd serve points won',
       'player2 2nd serve points total', 'player2 break points won',
       'player2 break points total', 'player2 service games played',
       'player2 1st serve return points won',
       'player2 1st serve return points total',
       'player2 2nd serve return points won',
       'player2 2nd serve return points total',
       'player2 break points converted won',
       'player2 break points converted total', 'player2 return games played',
       'player2 total service points won',
       'player2 total service points total', 'player2 total return points won',
       'player2 total return points total', 'player2 total points won',
       'player2 total points total'],
      dtype='object')

In [ ]:
df["winner"] == player

0       False
1        True
2        True
3       False
4       False
5       False
6        True
7        True
8        True
9        True
10       True
11       True
12      False
13       True
14       True
15       True
16      False
17       True
18       True
19      False
20       True
21      False
22       True
23      False
24      False
25       True
26      False
27      False
28      False
29      False
        ...
1149     True
1150    False
1151     True
1152     True
1153     True
1154     True
1155     True
1156     True
1157     True
1158     True
1159     True
1160     True
1161     True
1162     True
1163     True
1164     True
1165     True
1166     True
1167     True
1168    False
1169     True
1170     True
1171     True
1172     True
1173     True
1174    False
1175     True
1176     True
1177     True
1178    False
Name: winner, Length: 1179, dtype: bool

In [ ]:
df['win'] = df['winner'] == player
df['win'].tail()

1174    False
1175     True
1176     True
1177     True
1178    False
Name: win, dtype: bool

In [ ]:
("{player} has won {vic:.0f}% "
               "of his ATP matches.").format(
                player=player, vic=100*df['win'].mean())

'Roger Federer has won 82% of his ATP matches.'

In [ ]:
df['dblfaults'] = (df['player1 double faults'] /
                   df['player1 total points total'])

In [ ]:
df['dblfaults'].tail()

1174    0.018116
1175    0.000000
1176    0.000000
1177    0.011561
1178         NaN
Name: dblfaults, dtype: float64

In [ ]:
gb = df.groupby('year')

In [ ]:
gb['dblfaults'].mean()

year
1998    0.021580
1999    0.023588
2000    0.021473
2001    0.017495
2002    0.016521
2003    0.018611
2004    0.013195
2005    0.010575
2006    0.007639
2007    0.007388
2008    0.005887
2009    0.010379
2010    0.009185
2011    0.009136
2012    0.009365
Name: dblfaults, dtype: float64

**Exercício:**

1. Construa uma tabela com o número de vitórias e derrotas de Federer para cada tipo de terreno.